### PR TITLE
refactor H2SO4 solution parameters

### PR DESCRIPTION
**Pull request by trontrytel**
This updates the functions in `Common` to the new way of handling free parameters.

### CODE REVIEW

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors cancel

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Review by amylu00 — APPROVED** [review]

**Review by nefrathenrici — APPROVED** [review]

**Pull request merged**
