### PR TITLE
combine box and parcel models

### PR DESCRIPTION
**Pull request by amylu00**
## Content

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by amylu00** [comment]
Do we want to rename everything? The default will be parcel settings.

**Comment by trontrytel** [comment]
I think the docs error is unrelated to the PR... Also, I'm not getting it locally. I'll try to pin the package versions

**Comment by trontrytel** [comment]
I changed some names to be more descriptive. Lmk if you like the new names. Looks good otherwise.

**Review by trontrytel — APPROVED** [review]
Lets see if I can get rid of the docs errors...

**Pull request merged**
