### PR TITLE
switch to using RootSolvers in docs

### PR DESCRIPTION
**Pull request by trontrytel**
We are now using RootSolvers in the P3 scheme. It can do the same thing as Roots, and we will have one less dependency to worry about. 

Closing https://github.com/CliMA/CloudMicrophysics.jl/issues/228

Also updating the documenter. I think the main thing is `makedocs(..., bib) -> makedocs(..., plugins=[bib])`

### CODE REVIEW

**Review by charleskawczynski — APPROVED** [review]
RootSolvers part looks fine to me. Note that the default tolerance is very small, so you may want to adjust it.

**Review by amylu00 — APPROVED** [review]

**Pull request merged**
