### PR TITLE
Fix package deps for a release

### PR DESCRIPTION
**Pull request by trontrytel**
Trying to fix:

```
Your new version pull request does not meet the guidelines for auto-merging. Please make sure that you have read the General registry README and the AutoMerge guidelines. The following guidelines were not met:
The following dependencies do not have a [compat] entry that is upper-bounded and only includes a finite number of breaking releases: CLIMAParameters, NonlinearSolve
```

### CODE REVIEW

**Comment by trontrytel** [comment]
bors try

**Review by nefrathenrici — APPROVED** [review]

**Comment by nefrathenrici** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try

**Pull request merged**
