### PR TITLE
try using components in codecov

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Comment by trontrytel** [comment]
I wish I could have a codecov badge generated only for the `src` folder. But maybe it's enough bikeshedding for today

**Comment by Sbozzolo** [comment]
Can you add two lines of comments at the top of the yml file to explain what's accomplishing?

**Review by nefrathenrici — APPROVED** [review]
Looks good! Though it is too bad the overall codecov percent doesn't seem to change

**Comment by trontrytel** [comment]
> Looks good! Though it is too bad the overall codecov percent doesn't seem to change

Yes. I'm sad I couldn't figure out how to get a badge that is based only on the `src` coverage report.

**Pull request merged**
