### PR TITLE
fixing immersion freezing production rate

### PR DESCRIPTION
**Pull request by amylu00**
## Content

- immersion freezing production rate proportional to INP surface area, _not_ the droplet's surface area

----
- [ ] I have read and checked the items on the review checklist.

### CODE REVIEW

**Comment by amylu00** [comment]
Before the fix:
Screenshot 2024-02-19 at 12 55 12 PM

After the fix:
Screenshot 2024-02-19 at 12 55 44 PM

`q_liq` is stabilized for mono disperse size distribution now. Ice supersaturation and `q_ice` match up better, but not sure if that is an expected behavior or not.

**Comment by amylu00** [comment]
Also fixing the deposition warning issue here since it's only a few lines of print code. If you think it's better to have it in a separate PR, I can do that

**Review by trontrytel — APPROVED** [review]
LGTM!

We could also have a separate parameter for the assumed aeorsol area and not have to re-use the r_nuc which is used in the deposition freezing. I think this will be helpful once you start running simulations with more than just one mode of freezing.

Also, why are you changing the initial condition for the immersion freezing example?

Lmk if you need help adapting it to the new parcel setup. Tbh it might be easier to "manually" add your changes rather than try to rebase this

**Comment by amylu00** [comment]
> Also, why are you changing the initial condition for the immersion freezing example?

I was getting situations where there was very little to no ice nucleation for the monodisperse case. If that doesn't seem right, we can discuss it tomorrow?

**Pull request merged**
