### PR TITLE
Upgrade to new version of CLIMAParameters

### PR DESCRIPTION
**Pull request by trontrytel**
@charleskawczynski  - this passes all the tests and builds the docs on my local. 

Unfortunately something mysterious happened and I had to update the dependencies in Manifest file for docs. But we need to revert the dependencies in all toml files anyway, so I left it for now. Lets see how it goes in the CI

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Awesome. I'll register a new CLIMAParameters version, update Thermo, and we can update this PR.

**Comment by trontrytel** [comment]
> Awesome. I'll register a new CLIMAParameters version, update Thermo, and we can update this PR.

Great. Many thanks!

**Review by charleskawczynski — APPROVED** [review]
Looks great!

**Comment by trontrytel** [comment]
So now we should register a new release here and then fix ClimateMachine.jl?

**Pull request merged**
