### PR TITLE
Update to julia 1.9

### PR DESCRIPTION
**Pull request by trontrytel**

### CODE REVIEW

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
Seems to be working modulo the error below. The init seems to work even with it.

```
LinearSolveCUDAExt [e24d4dde-ed20-5ee7-b465-f1dd73f9b6ba]
--
  | │  ┌ Error: JULIA_CUDA_USE_BINARYBUILDER is deprecated, and CUDA.jl always uses artifacts now.
  | │  │ To use a local installation, use overrides or preferences to customize the artifact.
  | │  │ Please check the CUDA.jl or Pkg.jl documentation for more details.
  | │  └ @ CUDA /central/scratch/esm/slurm-buildkite/cloudmicrophysics-ci/132/depot/gpu/packages/CUDA/tVtYo/src/initialization.jl:155
  | └
  | ┌ ArrayInterfaceCUDAExt [f78586ac-ba87-5ec7-b3a5-84bc1b258ee3]
  | │  ┌ Error: JULIA_CUDA_USE_BINARYBUILDER is deprecated, and CUDA.jl always uses artifacts now.
  | │  │ To use a local installation, use overrides or preferences to customize the artifact.
  | │  │ Please check the CUDA.jl or Pkg.jl documentation for more details.
  | │  └ @ CUDA /central/scratch/esm/slurm-buildkite/cloudmicrophysics-ci/132/depot/gpu/packages/CUDA/tVtYo/src/initialization.jl:155
  | └
  | ┌ Error: JULIA_CUDA_USE_BINARYBUILDER is deprecated, and CUDA.jl always uses artifacts now.
  | │ To use a local installation, use overrides or preferences to customize the artifact.
  | │ Please check the CUDA.jl or Pkg.jl documentation for more details.
  | └ @ CUDA /central/scratch/esm/slurm-buildkite/cloudmicrophysics-ci/132/depot/gpu/packages/CUDA/tVtYo/src/initialization.jl:155
  | CUDA runtime 12.1, artifact installation
  | CUDA driver 12.2
  | NVIDIA driver 535.54.3
  |  
  | CUDA libraries:
  | - CUBLAS: 12.1.3
  | - CURAND: 10.3.2
  | - CUFFT: 11.0.2
  | - CUSOLVER: 11.4.5
  | - CUSPARSE: 12.1.0
  | - CUPTI: 18.0.0
  | - NVML: 12.0.0+535.54.3
  |  
  | Julia packages:
  | - CUDA: 4.4.0
  | - CUDA_Driver_jll: 0.5.0+1
  | - CUDA_Runtime_jll: 0.6.0+0
  |  
  | Toolchain:
  | - Julia: 1.9.2
  | - LLVM: 14.0.6
  | - PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0, 7.1, 7.2, 7.3, 7.4, 7.5
  | - Device capability support: sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80, sm_86
  |  
  | Environment:
  | - JULIA_CUDA_USE_BINARYBUILDER: false
  |  
  | 1 device:
  | 0: Tesla P100-PCIE-16GB (sm_60, 15.893 GiB / 16.000 GiB available)
  | ┌ Error: JULIA_CUDA_USE_BINARYBUILDER is deprecated, and CUDA.jl always uses artifacts now.
  | │ To use a local installation, use overrides or preferences to customize the artifact.
  | │ Please check the CUDA.jl or Pkg.jl documentation for more details.


```

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Comment by nefrathenrici** [comment]
bors try-

**Comment by nefrathenrici** [comment]
bors try

**Review by nefrathenrici — APPROVED** [review]

**Review by charleskawczynski — APPROVED** [review]

**Comment by charleskawczynski** [comment]
I think the [bors toml](https://github.com/CliMA/CloudMicrophysics.jl/blob/main/bors.toml#L2-L4) needs updated

**Comment by trontrytel** [comment]
Updated the names

> I think the [bors toml](https://github.com/CliMA/CloudMicrophysics.jl/blob/main/bors.toml#L2-L4) needs updated

Thank you for the hint! If you think about it, it makes sense that the names should match :joy:

I increased the timeout limit for good luck.

**Comment by charleskawczynski** [comment]
bors try-

**Pull request merged**
