### PR TITLE
Add cluster CI setup

### PR DESCRIPTION
**Pull request by jakebolewski**
Start of #19

### CODE REVIEW

**Comment by jakebolewski** [comment]
bors try

**Comment by jakebolewski** [comment]
@trontrytel this should work similarly to the ClimateMachine repo, just need to configure the agent for CPU / GPU environments: 
See https://github.com/CliMA/ClimaCore.jl/blob/main/.buildkite/pipeline.yml#L65

Feel free just to add to this, but this should be all that is required to get started.

**Comment by trontrytel** [comment]
> @trontrytel this should work similarly to the ClimateMachine repo, just need to configure the agent for CPU / GPU environments:
> See https://github.com/CliMA/ClimaCore.jl/blob/main/.buildkite/pipeline.yml#L65
> 
> Feel free just to add to this, but this should be all that is required to get started.

Thank you! I will

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Comment by trontrytel** [comment]
@jakebolewski and @charleskawczynski this executes all the unit tests we have for the package on cpu and gpu

**Review by trontrytel — APPROVED** [review]
@jakebolewski , just realised I can't ask you for review cause it was you who opened the PR :)

Can I merge it?

**Review by charleskawczynski — APPROVED** [review]

**Comment by jakebolewski** [comment]
Sure LGTM

**Pull request merged**
