### PR TITLE
Widen compat entries, update deps, fix gpu test

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR widens DocStringExtensions compat entry for the latest version

### CODE REVIEW

**Review by trontrytel — APPROVED** [review]

**Comment by trontrytel** [comment]
Thats the same error that I saw when trying to update to Julia 1.8: https://github.com/CliMA/CloudMicrophysics.jl/pull/80

**Comment by charleskawczynski** [comment]
> Member

Ahhh, interesting. It looks like inference has somehow changed. Let me see...

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Comment by charleskawczynski** [comment]
bors try

**Review by trontrytel — APPROVED** [review]
Congratulations! So it was the parameters  types that were the issue?

**Pull request merged**
